# Generated by Django 3.2.10 on 2021-12-19 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('puser', models.CharField(max_length=60)),
                ('pname', models.CharField(max_length=60)),
                ('pnum', models.CharField(max_length=60)),
                ('pcate', models.CharField(max_length=60)),
                ('plevel', models.CharField(max_length=60)),
                ('pmanager', models.CharField(max_length=60)),
                ('ppay', models.CharField(max_length=60)),
            ],
        ),
    ]
